### ISSUE TITLE
Stage 3 lagged out my PC

### ISSUE THREAD

**Issue by RylanYancey** [rparrett/pixie_wrangler#1]
Stage 3 Lagged out my Laptop. 

Specs:

Ryzen 7 5800
GTX 1650 
16gb ram

It lagged out when I sent the pixies.

**Comment by rparrett** [comment]
Thanks for the report.

Are you playing on twitch? And if so, what browser (and version) are you using?

Level 3 definitely ramps up the amount of pixies on the screen, and the collision / traffic code is extremely naive, but I'm surprised to see a report of a machine with those specs having issues.

There is a known issue where having the firefox developer tools open while playing noticeably slows things down.

**Comment by RylanYancey** [comment]
I just downloaded the src code from github and ran it.

**Comment by rparrett** [comment]
Did you run with the release profile? i.e.
```cargo make --profile release run```
or
```cargo run --release``
?

**Comment by RylanYancey** [comment]
ah, I did not. That may have been why. I'll try running it from Itch.io

**Comment by rparrett** [comment]
Release mode makes a huge difference, so some slowness without it is expected.

**Comment by rparrett** [comment]
Thanks again for motivating me to deal with some of the performance issues.

I've addressed this in a few ways:

https://github.com/rparrett/pixie_wrangler/commit/291e07c517420560e4a97afc0111526b7b778c6f adds optimizations in debug builds just for our dependencies (e.g. the bevy engine itself) as described in [the performance section of the "bevy cheatbook"](https://bevy-cheatbook.github.io/pitfalls/performance.html)

https://github.com/rparrett/pixie_wrangler/commit/651ab0154de58831791d029e0380494a992cde0a adds a spatial index for collision detection in the laziest way possible, which still turns out to be a huge win.
